routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

$blocked = static function() {
    Route::get('/', static function () {
        return view("block");
    });
};

Route::group(['domain' => 'www.expovino.com.pe'], $blocked);
Route::group(['domain' => 'expovino.com.pe'], $blocked);

Route::get('/', function () {
    if (!\auth()->guest()) {
        return \route('home');
    }
    return view('auth.login');
})->middleware('guest');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/cronograma', 'HomeController@crono')->name('crono');

Route::resource('bodegas', 'BrandsController');
Route::resource('productos', 'ProductsController');
Route::resource('agenda', 'TempSchedulesController');

//Wines
Route::get('cata-vino', 'WinesController@cata')
    ->name('wines.cata-vino');
Route::get('cata-vino/detalle/{slug}', 'WinesController@cataDetails')->name('wines.cata-vino.details');
Route::get('experto-vino', 'WinesController@experto')
    ->middleware('role:catador|super-admin')
    ->name('wines.experto-vino');
Route::get('hablemos-vino', 'WinesController@hablemos')->name('wines.hablemos-vino');
Route::get('hablemos-vino/detalle/{slug}', 'WinesController@hablemosDetails')
    ->name('wines.hablemos-vino.details');
Route::get('viva-vino', 'WinesController@viva')->name('wines.viva-vino');

//Shoppingcart
Route::get('carrito', 'ShoppingcartController@index')->name('shoppingcart.index');
Route::get('shoppingcart/add/{product}', 'ShoppingcartController@add')->name('shoppingcart.add');
Route::get('shoppingcart/remove/{product}', 'ShoppingcartController@remove')->name('shoppingcart.remove');
Route::get('shoppingcart/update/{rowId}/{qty}',
    'ShoppingcartController@quantity')->name('shoppingcart.quantity.update');
Route::get('shoppingcart/store', 'ShoppingcartController@store')->name('shoppingcart.store');

// Products
Route::get('productos/update/price/{id}', 'ProductsController@price')->middleware(['role:super-admin']);

//Imports
Route::get('imports/brands', 'ImportsController@brands')->name('import.brands');
Route::get('imports/products', 'ImportsController@products')->name('import.products');

//Boxes
Route::get('boxes', 'BoxesController@index')->name('boxes.index');
Route::get('boxes/{slug}', 'BoxesController@show')->name('boxes.show');

// Gourmets
Route::get('gourmet', 'GourmetsController@index')->name('gourmets.index');
Route::get('gourmet/{slug}', 'GourmetsController@show')->name('gourmets.show');
route::get('gourmet/producto/{productSlug}', "GourmetsController@product")->name('gourmets.product.show');

// Copas
Route::middleware(['auth', 'history'])->get('copas/copa-red-wine-56cl', function () {
    return view('pages.products.show')->with(
        'product', \App\Models\Product::with('brand')
        ->with('categories')
        ->whereSlug('copa-red-wine-56cl')
        ->first()
    );
})->name('copas');

//Route::get('file', function() {
//    return view('file');
//});
//
//Route::post('upload', function() {
//    $file = request()->file('file');
//
//    \Optix\Media\MediaUploader::fromFile($file)->upload();
//});

Auth::routes();

app/Http/Controllers/BrandsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\BrandCreateRequest;
use App\Http\Requests\BrandUpdateRequest;
use App\Repositories\Contracts\BrandRepository;
use App\Validators\BrandValidator;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Response;
use Illuminate\View\View;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;

/**
 * Class BrandsController.
 *
 * @package namespace App\Http\Controllers;
 */
class BrandsController extends Controller
{
    /**
     * @var BrandRepository
     */
    protected $repository;

    /**
     * @var BrandValidator
     */
    protected $validator;

    /**
     * BrandsController constructor.
     *
     * @param BrandRepository $repository
     * @param BrandValidator $validator
     */
    public function __construct(BrandRepository $repository, BrandValidator $validator)
    {
        $this->middleware(['auth', 'history']);

        $this->repository = $repository;
        $this->validator = $validator;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|JsonResponse|Response|View
     */
    public function index()
    {
        $this->repository->pushCriteria(app('Prettus\Repository\Criteria\RequestCriteria'));
        $brands = $this->repository->with(['products', 'country'])->paginate(6);

        if (request()->wantsJson()) {
            return response()->json($brands);
        }

        return view('brands.index', compact('brands'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param BrandCreateRequest $request
     *
     * @return JsonResponse|RedirectResponse|Response
     */
    public function store(BrandCreateRequest $request)
    {
        try {

            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_CREATE);

            $brand = $this->repository->create($request->all());

            $response = [
                'message' => 'Brand created.',
                'data' => $brand->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->back()->with('message', $response['message']);
        } catch (ValidatorException $e) {
            if ($request->wantsJson()) {
                return response()->json([
                    'error' => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param string $slug
     *
     * @return Application|Factory|JsonResponse|Response|View
     */
    public function show(string $slug)
    {
        $brand = $this->repository->findByField('slug', $slug)->first();
        $products = $brand->products()->paginate(6);

        if (request()->wantsJson()) {
            return response()->json([
                'data' => $brand,
            ]);
        }

        return view('pages.brands.show', compact('brand', 'products'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @return Application|Factory|Response|View
     */
    public function edit(int $id)
    {
        $brand = $this->repository->find($id);

        return view('brands.edit', compact('brand'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param BrandUpdateRequest $request
     * @param int $id
     *
     * @return JsonResponse|RedirectResponse|Response
     */
    public function update(BrandUpdateRequest $request, int $id)
    {
        try {

            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_UPDATE);

            $brand = $this->repository->update($request->all(), $id);

            $response = [
                'message' => 'Brand updated.',
                'data' => $brand->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->back()->with('message', $response['message']);
        } catch (ValidatorException $e) {

            if ($request->wantsJson()) {

                return response()->json([
                    'error' => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return JsonResponse|RedirectResponse|Response
     */
    public function destroy(int $id)
    {
        $deleted = $this->repository->delete($id);

        if (request()->wantsJson()) {

            return response()->json([
                'message' => 'Brand deleted.',
                'deleted' => $deleted,
            ]);
        }

        return redirect()->back()->with('message', 'Brand deleted.');
    }
}

app/Http/Livewire/Boxes/Search.php
<?php

namespace App\Http\Livewire\Boxes;

use App\Models\Product;
use Gloudemans\Shoppingcart\Facades\Cart;
use Illuminate\View\View;
use Livewire\Component;

class Search extends Component
{
    /**
     * @var int $perPage
     */
    public int $perPage = 6;

    /**
     * @var string $precio
     */
    public string $precio= '';

    /**
     * @var string[] $listeners
     */
    protected $listeners = [
        'load-more-boxes' => 'loadMoreBoxes'
    ];

    /**
     * Get the view / contents that represent the component.
     *
     * @return View|string
     */
    public function render()
    {
        return view('livewire.boxes.search', [
            'products' => Product::boxes()
                ->orderBy('price', !empty($this->precio) ? $this->precio : 'asc')
                ->get()
        ]);
    }

    /**
     * Load more boxes.
     */
    public function loadMoreBoxes(): void
    {
        $this->perPage += 3;
    }

    /**
     * Add product to shoppingcart.
     *
     * @param int $productId
     */
    public function addProduct(int $productId): void
    {
        Cart::add(Product::find($productId), 1);

        $this->emit('productAdded');
    }
}

app/Http/Livewire/Brand/Search.php
<?php

namespace App\Http\Livewire\Brand;

use App\Helpers\Categories;
use App\Models\Brand;
use App\Models\Country;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Collection;
use Illuminate\View\View;
use Livewire\Component;
use Livewire\WithPagination;

class Search extends Component
{
    use WithPagination;

    /**
     * @var int $perPage
     */
    public int $perPage = 6;

    /**
     * @var bool $showVino
     */
    public bool $showVino = true;

    /**
     * @var string[] $listeners
     */
    protected $listeners = [
        'load-more' => 'loadMore',
        'reset-filters' => 'resetFilters',
    ];

    /**
     * @var string[]
     */
    public array $filter = [
        'tipo' => '',
        'vino' => '',
        'pais' => '',
        'exclusivo' => '',
    ];

    /**
     * @var string $tipo
     */
    public string $tipo = '';

    /**
     * @var $brands
     */
    protected $brands;

    /**
     * @var Collection $countries
     */
    protected Collection $countries;

    /**
     * @var string $search
     */
    public string $search = '';

    /**
     * @var string[]
     */
    protected $queryString = [
        'search' => ['except' => ''],
        'tipo' => ['except' => ''],
        'page' => ['except' => 1]
    ];

    /**
     * mount component.
     */
    public function mount(): void
    {
        $this->search = '';

        if (session()->has('global_type_product')) {
            $this->filter['tipo'] = session()->get('global_type_product');
        } else {
            $this->filter['tipo'] = 'vino';
        }

        if (session()->has('exclusivo')) {
            session()->forget('exclusivo');
        }

        $this->filter['pais'] = '';
        $this->filter['vino'] = '';
    }

    /**
     * @return Application|Factory|View
     */
    public function render()
    {

        if (session()->has('global_wine_type')) {
            session()->forget('global_wine_type');
        }

        $this->brands = Brand::productType($this->filter['tipo']);

        if (!empty($this->search)) {
            $this->brands = $this->brands->where('name', 'like', '%' . $this->search . '%');
        }

        if (!empty($this->filter['pais'])) {
            $this->brands = $this->brands->byCountry($this->filter['pais']);
        }

        if(!empty($this->filter['vino'])) {
            session(['global_wine_type' => $this->filter['vino']]);

            $this->brands = $this->brands->whereHas('products.categories', function (Builder $query) {
               $query->whereIn('slug', [$this->filter['vino']]);
            });
        }

        if ($this->filter['exclusivo'] ) {
            session(['exclusivo' => true]);

            $this->brands = $this->brands->byExclusive();
        }

        if (!empty($this->filter['tipo'])) {
            if (session()->has('global_type_product') && session()->get('global_type_product') !== $this->filter['tipo']) {
                $this->emit('reset-filters');
            }

            session(['global_type_product' => $this->filter['tipo']]);

            $this->countries = Country::countryByProductType($this->filter['tipo'])->get();
        }

        if (session()->has('global_type_product') && session()->get('global_type_product') !== 'vino') {
            $this->showVino = false;
        } else {
            $this->showVino = true;
        }

        // show only products with shopping_sku != null.
        $this->brands = $this->brands->whereHas('products', function (Builder $query) {
            $query->whereNotNull('shopping_sku');
        });

        // Order brands by name asc
        $this->brands = $this->brands->orderBy('name', 'asc');

        return view('livewire.brand.search', [
            'brands' => $this->brands->paginate($this->perPage),
            'productTypes' => Categories::getCategoryByRootId(1)
                ->except(['boxes', 'gourmet', 'copas']),
            'countries' => $this->countries
        ]);
    }

    /**
     * @return string
     */
    public function paginationView(): string
    {
        return 'vendor.pagination.expovinos';
    }

    /**
     * Reset pagination.
     */
    public function updatingSearch(): void
    {
        $this->resetPage();
    }

    /**
     * Reset pagination where filter changed.
     */
    public function updatingFilter(): void
    {
        $this->resetPage();
    }

    /**
     * Load more content.
     */
    public function loadMore(): void
    {
        $this->perPage += 3;
    }

    /**
     * Reset all filters.
     */
    public function resetFilters(): void
    {
        $this->search = '';
        $this->filter['pais'] = '';
        $this->filter['vino'] = '';
        $this->filter['exclusivo'] = '';
    }
}

app/Http/Livewire/Gourmets/Products/Search.php
<?php

namespace App\Http\Livewire\Gourmets\Products;

use App\Models\Product;
use Gloudemans\Shoppingcart\Facades\Cart;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\View\View;
use Livewire\Component;
use Livewire\WithPagination;

class Search extends Component
{
    use WithPagination;

    /**
     * @var int $perPage
     */
    public int $perPage = 6;

    /**
     * @var string[] $listeners
     */
    protected $listeners = [
        'load-more-product-gourmet' => 'loadMoreProductGourmet',
        'reset-filters-gourmet-brand' => 'resetFiltersGourmetBrand'
    ];

    /**
     * @var string[]
     */
    public array $filter = [
        'precio' => '',
        'exclusivo' => '',
    ];

    /**
     * @var string $slug
     */
    public string $slug;

    /**
     * @param string $slug
     */
    public function mount(string $slug): void
    {
        $this->slug = $slug;

        $this->filter['precio'] = '';
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return View|string
     */
    public function render()
    {
        $products = Product::whereHas('brand', function (Builder $query) {
            $query->where('slug', $this->slug);
        });

        if ($this->filter['exclusivo']) {
            $products = $products->where('exclusive', true);
        }

        if ($this->filter['precio']) {
            $products = $products->orderBy('price', $this->filter['precio']);
        }

        if (session()->has('tipo_gourmet')) {
            $products = $products->wherehas('categories', function (Builder $builder) {
                $builder->where('slug', session()->get('tipo_gourmet'));
            });
        }

        $products = $products->whereNotNull('shopping_sku')->paginate($this->perPage);

        return view('livewire.gourmets.products.search', [
            'products' => $products,
        ]);
    }

    /**
     * Add product to shoppingcart.
     *
     * @param int $productId
     */
    public function addProduct(int $productId): void
    {
        Cart::add(Product::find($productId), 1);

        $this->emit('productAdded');
    }

    /**
     * Load mor products.
     */
    public function loadMoreProductGourmet(): void
    {
        $this->perPage += 3;
    }

    /**
     * reset filters
     */
    public function resetFiltersGourmetBrand(): void
    {
        $this->filter['precio'] = '';
        $this->filter['exclusivo'] = '';
    }
}

resources/views/livewire/brand/search.blade.php
<div>
    <section class="bodega-home">
        <!-- <div class="pasos-compra">
            <div class="content">
                <fieldset>
                    <legend>
                        <h2>Cómo comprar en el expovino</h2>
                    </legend>
                    <div class="content-pasos">
                        <div class="paso">
                            <div class="num">1</div>
                            <div class="paso-text">
                                <img src="{{ asset("images/paso_01.png") }}" alt="">
                                <p>Añade a tu carrito de compras tus vinos preferidos</p>
                            </div>
                        </div>
                        <div class="paso">
                            <div class="num">2</div>
                            <div class="paso-text">
                                <img src="{{ asset("images/paso_02.png") }}" alt="">
                                <p>Revisa tu carrito para validar tus productos</p>
                            </div>
                        </div>
                        <div class="paso">
                            <div class="num">3</div>
                            <div class="paso-text">
                                <img src="{{ asset("images/paso_03.png") }}" alt="">
                                <p>Serás redirigido a Wong.pe para finalizar tu compra</p>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div> -->
        <div id="resultados"></div>

        <div class="content content-bodega">
            <h2>Mundo de vinos y licores</h2>
            <p>Descubre toda la variedad de nuestra bodega con descuentos <br>exclusivos para ti.</p>

            <div class="filtros">
                <div class="content">
                    <div class="filtro-ppal">
                        <label for="tipoBebida">Tipo de bebida:</label>
                        <select wire:model="filter.tipo" id="tipoBebida">
                            @foreach($productTypes as $slug => $name)
                                <option value="{{ $slug }}">{{ $name }}</option>
                            @endforeach
                        </select>
                    </div>

                    @if((new \Jenssegers\Agent\Agent())->isDesktop())
                    <div class="otros-filtros solo-desktop">
                        <label>filtrar por:</label>
                        <div class="control-filter buscador">
                            <label>
                                <input wire:model.debounce.500ms="search" type="text" placeholder="Bodega / Marca"
                                       style="margin: 0; width: 150px">
                            </label>
                        </div>
                        <div class="control-filter">
                            <label for="pais" style="display: none;"></label>
                            <select wire:model="filter.pais" id="pais" class="pais">
                                <option value="">País</option>
                                @foreach($countries as $country)
                                    <option value="{{ $country->slug }}">{{ $country->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        @if($showVino)
                            <div class="control-filter">
                                <label for="tipoVino" style="display: none;"></label>
                                <select wire:model="filter.vino" id="tipoVino" class="tipo-vino">
                                    <option value="">Tipo</option>
                                    <option value="tinto">Tinto</option>
                                    <option value="blanco">Blanco</option>
                                    <option value="rosado">Rosado</option>
                                    <option value="espumante">Espumante</option>
                                </select>
                            </div>
                        @endif
                        <div class="control-filter">
                            <div class="check-custom">
                                <input type="checkbox" wire:model="filter.exclusivo" id="excluisividad">
                                <label for="excluisividad">Exclusivos</label>
                            </div>
                        </div>
                    </div>
                    @endif

                    <div class="solo-mobile abrir-filtros">
                        <a href="javascript:void(0)" class="mostrar">
                            <img src="{{ asset("images/filtro.png") }}" alt>
                            filtrar
                        </a>
                    </div>
                </div>
            </div>

            @if(isset($brands))
                <div class="resultados">
                    <div id="content-result-brands" class="content-result">
                        @foreach($brands as $brand)
                            <div class="item">
                                <a href="{{ route("bodegas.show", $brand->slug ) }}" class="item-link">
                                    <img src="{{ asset("brands/{$brand->logo}") }}" alt="{{ $brand->name }}">
                                    <h3>{{ $brand->name }}
                                        <br>
                                        <p class="country solo-mobile">
                                            <img src="{{ asset("images/" . $brand->country->flag) }}"
                                                 alt="{{ $brand->country->name }}">
                                            {{ $brand->country->name }}
                                        </p>
                                    </h3>
                                    <p>{{ Str::limit($brand->excerpt, 100, "...") }}</p>
                                    <p class="country solo-desktop">
                                        <img src="{{ asset("images/" . $brand->country->flag) }}"
                                             alt="{{ $brand->country->name }}">
                                        {{ $brand->country->name }}
                                    </p>
                                    <span>
                                <img src="{{ asset("images/conoce_mas.png") }}" alt> Conoce más
                            </span>
                                </a>
                            </div>
                        @endforeach
                    </div>

                    @if($brands->hasPages())
                        <div class="onload-more">
                            <span style="cursor: pointer;" wire:click="$emit('load-more')">ver más</span>
                        </div>
                    @endif
                </div>
            @endif

        </div>

    </section>

    @if((new \Jenssegers\Agent\Agent())->isPhone())
    <section class="filtros-mobile solo-mobile">
        <div class="content">
            <div class="cabecera">
                <p>Filtros</p>
                <a href="javascript:void(0)" class="ocultar">
                    <img src="{{ asset("images/close.png") }}" alt="">
                </a>
            </div>
            <div class="filtros">
                <div class="control-filter buscador">
                    <label>
                        <label for="msearch" class="hide"></label>
                        <input id="msearch"
                               wire:model.defer="search"
                               type="text"
                               placeholder="Bodega / Marca">
                    </label>
                </div>
                <div class="exclusividad">
                    <label>
                        <input wire:model.defer="filter.exclusivo"
                               type="checkbox"
                               name="exclusividad"
                               class="filled-in"/>
                        <span>Exclusivos</span>
                    </label>
                </div>
                <div class="control-filter">
                    <label for="pais" style="display: none;"></label>
                    <select wire:model.defer="filter.pais" id="pais" class="pais">
                        <option value="">País</option>
                        @foreach($countries as $country)
                            <option value="{{ $country->slug }}">{{ $country->name }}</option>
                        @endforeach
                    </select>
                </div>
                @if($showVino)
                <div class="control-filter">
                    <label for="tipoVino" style="display: none;"></label>
                    <select wire:model.defer="filter.vino" id="tipoVino" class="tipo-vino">
                        <option value="">Tipo</option>
                        <option value="tinto">Tinto</option>
                        <option value="blanco">Blanco</option>
                        <option value="rosado">Rosado</option>
                        <option value="espumante">Espumante</option>
                    </select>
                </div>
                @endif
                <div class="control-filter">
                    <label for="porPrecio" style="display: none;"></label>
                    <select wire:model.defer="filter.precio" id="porPrecio" class="precio">
                        <option value="">Precio</option>
                        <option value="">de menor a mayor</option>
                        <option value="">de mayor a menor</option>
                    </select>
                </div>
                <div class="cta-btn">
                    <a id="buscar" href="javascript:void(0)" wire:click="render" class="filtrar">Buscar</a>
                    <a href="javascript:void(0)" wire:click="$emit('reset-filters')" class="limpiar">Limpiar filtros</a>
                </div>
            </div>
        </div>
    </section>
    @endif
</div>